name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Generate test report
        run: npm run test:report

      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment commands here

      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/tags/*'
        run: |
          echo "Deploying to production environment..."
          # Add your deployment commands here
